// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/logging"

	mock "github.com/stretchr/testify/mock"
)

// ActivityLogUsecase is an autogenerated mock type for the ActivityLogUsecase type
type ActivityLogUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, activity_log
func (_m *ActivityLogUsecase) Create(c context.Context, activity_log *domain.ActivityLog) error {
	ret := _m.Called(c, activity_log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ActivityLog) error); ok {
		r0 = rf(c, activity_log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *ActivityLogUsecase) CreateMany(c context.Context, items []domain.ActivityLog) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ActivityLog) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ActivityLogUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ActivityLogUsecase) Fetch(c context.Context) ([]domain.ActivityLog, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ActivityLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ActivityLog, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ActivityLog); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ActivityLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ActivityLogUsecase) FetchByID(c context.Context, ID string) (domain.ActivityLog, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ActivityLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ActivityLog, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ActivityLog); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ActivityLog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, activity_log
func (_m *ActivityLogUsecase) Update(c context.Context, activity_log *domain.ActivityLog) error {
	ret := _m.Called(c, activity_log)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ActivityLog) error); ok {
		r0 = rf(c, activity_log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewActivityLogUsecase creates a new instance of ActivityLogUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityLogUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityLogUsecase {
	mock := &ActivityLogUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
