// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/common"

	mock "github.com/stretchr/testify/mock"
)

// AddressAttributeRepository is an autogenerated mock type for the AddressAttributeRepository type
type AddressAttributeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, address_attribute
func (_m *AddressAttributeRepository) Create(c context.Context, address_attribute *domain.AddressAttribute) error {
	ret := _m.Called(c, address_attribute)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AddressAttribute) error); ok {
		r0 = rf(c, address_attribute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *AddressAttributeRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *AddressAttributeRepository) Fetch(c context.Context) ([]domain.AddressAttribute, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.AddressAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.AddressAttribute, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.AddressAttribute); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AddressAttribute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *AddressAttributeRepository) FetchByID(c context.Context, ID string) (domain.AddressAttribute, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.AddressAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.AddressAttribute, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.AddressAttribute); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.AddressAttribute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, address_attribute
func (_m *AddressAttributeRepository) Update(c context.Context, address_attribute *domain.AddressAttribute) error {
	ret := _m.Called(c, address_attribute)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AddressAttribute) error); ok {
		r0 = rf(c, address_attribute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddressAttributeRepository creates a new instance of AddressAttributeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressAttributeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressAttributeRepository {
	mock := &AddressAttributeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
