// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/common"

	mock "github.com/stretchr/testify/mock"
)

// AddressAttributeValueUsecase is an autogenerated mock type for the AddressAttributeValueUsecase type
type AddressAttributeValueUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, address_attribute_value
func (_m *AddressAttributeValueUsecase) Create(c context.Context, address_attribute_value *domain.AddressAttributeValue) error {
	ret := _m.Called(c, address_attribute_value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AddressAttributeValue) error); ok {
		r0 = rf(c, address_attribute_value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *AddressAttributeValueUsecase) CreateMany(c context.Context, items []domain.AddressAttributeValue) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.AddressAttributeValue) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *AddressAttributeValueUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *AddressAttributeValueUsecase) Fetch(c context.Context) ([]domain.AddressAttributeValue, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.AddressAttributeValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.AddressAttributeValue, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.AddressAttributeValue); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AddressAttributeValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *AddressAttributeValueUsecase) FetchByID(c context.Context, ID string) (domain.AddressAttributeValue, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.AddressAttributeValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.AddressAttributeValue, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.AddressAttributeValue); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.AddressAttributeValue)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, address_attribute_value
func (_m *AddressAttributeValueUsecase) Update(c context.Context, address_attribute_value *domain.AddressAttributeValue) error {
	ret := _m.Called(c, address_attribute_value)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AddressAttributeValue) error); ok {
		r0 = rf(c, address_attribute_value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddressAttributeValueUsecase creates a new instance of AddressAttributeValueUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressAttributeValueUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressAttributeValueUsecase {
	mock := &AddressAttributeValueUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
