// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// BackInStockSubscriptionUsecase is an autogenerated mock type for the BackInStockSubscriptionUsecase type
type BackInStockSubscriptionUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, back_in_stock_subscription
func (_m *BackInStockSubscriptionUsecase) Create(c context.Context, back_in_stock_subscription *domain.BackInStockSubscription) error {
	ret := _m.Called(c, back_in_stock_subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BackInStockSubscription) error); ok {
		r0 = rf(c, back_in_stock_subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *BackInStockSubscriptionUsecase) CreateMany(c context.Context, items []domain.BackInStockSubscription) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.BackInStockSubscription) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *BackInStockSubscriptionUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *BackInStockSubscriptionUsecase) Fetch(c context.Context) ([]domain.BackInStockSubscription, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.BackInStockSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BackInStockSubscription, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BackInStockSubscription); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BackInStockSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *BackInStockSubscriptionUsecase) FetchByID(c context.Context, ID string) (domain.BackInStockSubscription, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.BackInStockSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.BackInStockSubscription, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.BackInStockSubscription); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.BackInStockSubscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, back_in_stock_subscription
func (_m *BackInStockSubscriptionUsecase) Update(c context.Context, back_in_stock_subscription *domain.BackInStockSubscription) error {
	ret := _m.Called(c, back_in_stock_subscription)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BackInStockSubscription) error); ok {
		r0 = rf(c, back_in_stock_subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBackInStockSubscriptionUsecase creates a new instance of BackInStockSubscriptionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackInStockSubscriptionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BackInStockSubscriptionUsecase {
	mock := &BackInStockSubscriptionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
