// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/orders"

	mock "github.com/stretchr/testify/mock"
)

// BestSellersReportLineRepository is an autogenerated mock type for the BestSellersReportLineRepository type
type BestSellersReportLineRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, best_sellers_report_line
func (_m *BestSellersReportLineRepository) Create(c context.Context, best_sellers_report_line *domain.BestSellersReportLine) error {
	ret := _m.Called(c, best_sellers_report_line)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BestSellersReportLine) error); ok {
		r0 = rf(c, best_sellers_report_line)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *BestSellersReportLineRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *BestSellersReportLineRepository) Fetch(c context.Context) ([]domain.BestSellersReportLine, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.BestSellersReportLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BestSellersReportLine, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BestSellersReportLine); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BestSellersReportLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *BestSellersReportLineRepository) FetchByID(c context.Context, ID string) (domain.BestSellersReportLine, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.BestSellersReportLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.BestSellersReportLine, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.BestSellersReportLine); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.BestSellersReportLine)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, best_sellers_report_line
func (_m *BestSellersReportLineRepository) Update(c context.Context, best_sellers_report_line *domain.BestSellersReportLine) error {
	ret := _m.Called(c, best_sellers_report_line)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BestSellersReportLine) error); ok {
		r0 = rf(c, best_sellers_report_line)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBestSellersReportLineRepository creates a new instance of BestSellersReportLineRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBestSellersReportLineRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BestSellersReportLineRepository {
	mock := &BestSellersReportLineRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
