// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/blogs"

	mock "github.com/stretchr/testify/mock"
)

// BlogPostTagRepository is an autogenerated mock type for the BlogPostTagRepository type
type BlogPostTagRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, blog_post_tag
func (_m *BlogPostTagRepository) Create(c context.Context, blog_post_tag *domain.BlogPostTag) error {
	ret := _m.Called(c, blog_post_tag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlogPostTag) error); ok {
		r0 = rf(c, blog_post_tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *BlogPostTagRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *BlogPostTagRepository) Fetch(c context.Context) ([]domain.BlogPostTag, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.BlogPostTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BlogPostTag, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BlogPostTag); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BlogPostTag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *BlogPostTagRepository) FetchByID(c context.Context, ID string) (domain.BlogPostTag, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.BlogPostTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.BlogPostTag, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.BlogPostTag); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.BlogPostTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, blog_post_tag
func (_m *BlogPostTagRepository) Update(c context.Context, blog_post_tag *domain.BlogPostTag) error {
	ret := _m.Called(c, blog_post_tag)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlogPostTag) error); ok {
		r0 = rf(c, blog_post_tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBlogPostTagRepository creates a new instance of BlogPostTagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlogPostTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlogPostTagRepository {
	mock := &BlogPostTagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
