// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/blogs"

	mock "github.com/stretchr/testify/mock"
)

// BlogPostUsecase is an autogenerated mock type for the BlogPostUsecase type
type BlogPostUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, acl_record
func (_m *BlogPostUsecase) CreateMany(c context.Context, acl_record []domain.BlogPostTag) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.BlogPostTag) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, blog_post
func (_m *BlogPostUsecase) Create(c context.Context, blog_post *domain.BlogPost) error {
	ret := _m.Called(c, blog_post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlogPost) error); ok {
		r0 = rf(c, blog_post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *BlogPostUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *BlogPostUsecase) Fetch(c context.Context) ([]domain.BlogPost, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.BlogPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BlogPost, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BlogPost); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BlogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *BlogPostUsecase) FetchByID(c context.Context, ID string) (domain.BlogPost, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.BlogPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.BlogPost, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.BlogPost); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.BlogPost)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, blog_post
func (_m *BlogPostUsecase) Update(c context.Context, blog_post *domain.BlogPost) error {
	ret := _m.Called(c, blog_post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlogPost) error); ok {
		r0 = rf(c, blog_post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBlogPostUsecase creates a new instance of BlogPostUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlogPostUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlogPostUsecase {
	mock := &BlogPostUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
