// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/messages"

	mock "github.com/stretchr/testify/mock"
)

// CampaignUsecase is an autogenerated mock type for the CampaignUsecase type
type CampaignUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, campaign
func (_m *CampaignUsecase) Create(c context.Context, campaign *domain.Campaign) error {
	ret := _m.Called(c, campaign)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Campaign) error); ok {
		r0 = rf(c, campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CampaignUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CampaignUsecase) Fetch(c context.Context) ([]domain.Campaign, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Campaign, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Campaign); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CampaignUsecase) FetchByID(c context.Context, ID string) (domain.Campaign, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Campaign, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Campaign); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.Campaign)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, campaign
func (_m *CampaignUsecase) Update(c context.Context, campaign *domain.Campaign) error {
	ret := _m.Called(c, campaign)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Campaign) error); ok {
		r0 = rf(c, campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCampaignUsecase creates a new instance of CampaignUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCampaignUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CampaignUsecase {
	mock := &CampaignUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
