// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/security"

	mock "github.com/stretchr/testify/mock"
)

// CaptchaSettingsRepository is an autogenerated mock type for the CaptchaSettingsRepository type
type CaptchaSettingsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, acl_record
func (_m *CaptchaSettingsRepository) CreateMany(c context.Context, acl_record []domain.CaptchaSettings) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.CaptchaSettings) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, capcha_settings
func (_m *CaptchaSettingsRepository) Create(c context.Context, capcha_settings *domain.CaptchaSettings) error {
	ret := _m.Called(c, capcha_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CaptchaSettings) error); ok {
		r0 = rf(c, capcha_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CaptchaSettingsRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CaptchaSettingsRepository) Fetch(c context.Context) ([]domain.CaptchaSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CaptchaSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CaptchaSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CaptchaSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CaptchaSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CaptchaSettingsRepository) FetchByID(c context.Context, ID string) (domain.CaptchaSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CaptchaSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CaptchaSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CaptchaSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CaptchaSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, capcha_settings
func (_m *CaptchaSettingsRepository) Update(c context.Context, capcha_settings *domain.CaptchaSettings) error {
	ret := _m.Called(c, capcha_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CaptchaSettings) error); ok {
		r0 = rf(c, capcha_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCaptchaSettingsRepository creates a new instance of CaptchaSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaptchaSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CaptchaSettingsRepository {
	mock := &CaptchaSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
