// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// CatalogSettingsRepository is an autogenerated mock type for the CatalogSettingsRepository type
type CatalogSettingsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, acl_record
func (_m *CatalogSettingsRepository) CreateMany(c context.Context, acl_record []domain.CatalogSettings) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.CatalogSettings) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, catalog_settings
func (_m *CatalogSettingsRepository) Create(c context.Context, catalog_settings *domain.CatalogSettings) error {
	ret := _m.Called(c, catalog_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CatalogSettings) error); ok {
		r0 = rf(c, catalog_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CatalogSettingsRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CatalogSettingsRepository) Fetch(c context.Context) ([]domain.CatalogSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CatalogSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CatalogSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CatalogSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CatalogSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CatalogSettingsRepository) FetchByID(c context.Context, ID string) (domain.CatalogSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CatalogSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CatalogSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CatalogSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CatalogSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, catalog_settings
func (_m *CatalogSettingsRepository) Update(c context.Context, catalog_settings *domain.CatalogSettings) error {
	ret := _m.Called(c, catalog_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CatalogSettings) error); ok {
		r0 = rf(c, catalog_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCatalogSettingsRepository creates a new instance of CatalogSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogSettingsRepository {
	mock := &CatalogSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
