// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// CategoryTemplateUsecase is an autogenerated mock type for the CategoryTemplateUsecase type
type CategoryTemplateUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, category_template
func (_m *CategoryTemplateUsecase) Create(c context.Context, category_template *domain.CategoryTemplate) error {
	ret := _m.Called(c, category_template)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CategoryTemplate) error); ok {
		r0 = rf(c, category_template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *CategoryTemplateUsecase) CreateMany(c context.Context, items []domain.CategoryTemplate) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.CategoryTemplate) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CategoryTemplateUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CategoryTemplateUsecase) Fetch(c context.Context) ([]domain.CategoryTemplate, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CategoryTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CategoryTemplate, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CategoryTemplate); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CategoryTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CategoryTemplateUsecase) FetchByID(c context.Context, ID string) (domain.CategoryTemplate, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CategoryTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CategoryTemplate, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CategoryTemplate); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CategoryTemplate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, category_template
func (_m *CategoryTemplateUsecase) Update(c context.Context, category_template *domain.CategoryTemplate) error {
	ret := _m.Called(c, category_template)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CategoryTemplate) error); ok {
		r0 = rf(c, category_template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCategoryTemplateUsecase creates a new instance of CategoryTemplateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryTemplateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryTemplateUsecase {
	mock := &CategoryTemplateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
