// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/orders"

	mock "github.com/stretchr/testify/mock"
)

// CheckoutAttributeUsecase is an autogenerated mock type for the CheckoutAttributeUsecase type
type CheckoutAttributeUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, acl_record
func (_m *CheckoutAttributeUsecase) CreateMany(c context.Context, acl_record []domain.CheckoutAttribute) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.CheckoutAttribute) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, checkout_attribute
func (_m *CheckoutAttributeUsecase) Create(c context.Context, checkout_attribute *domain.CheckoutAttribute) error {
	ret := _m.Called(c, checkout_attribute)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CheckoutAttribute) error); ok {
		r0 = rf(c, checkout_attribute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CheckoutAttributeUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CheckoutAttributeUsecase) Fetch(c context.Context) ([]domain.CheckoutAttribute, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CheckoutAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CheckoutAttribute, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CheckoutAttribute); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CheckoutAttribute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CheckoutAttributeUsecase) FetchByID(c context.Context, ID string) (domain.CheckoutAttribute, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CheckoutAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CheckoutAttribute, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CheckoutAttribute); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CheckoutAttribute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, checkout_attribute
func (_m *CheckoutAttributeUsecase) Update(c context.Context, checkout_attribute *domain.CheckoutAttribute) error {
	ret := _m.Called(c, checkout_attribute)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CheckoutAttribute) error); ok {
		r0 = rf(c, checkout_attribute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCheckoutAttributeUsecase creates a new instance of CheckoutAttributeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckoutAttributeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckoutAttributeUsecase {
	mock := &CheckoutAttributeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
