// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/directory"

	mock "github.com/stretchr/testify/mock"
)

// CurrencySettingsUsecase is an autogenerated mock type for the CurrencySettingsUsecase type
type CurrencySettingsUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, currency_settings
func (_m *CurrencySettingsUsecase) Create(c context.Context, currency_settings *domain.CurrencySettings) error {
	ret := _m.Called(c, currency_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CurrencySettings) error); ok {
		r0 = rf(c, currency_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *CurrencySettingsUsecase) CreateMany(c context.Context, items []domain.CurrencySettings) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.CurrencySettings) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CurrencySettingsUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CurrencySettingsUsecase) Fetch(c context.Context) ([]domain.CurrencySettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CurrencySettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CurrencySettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CurrencySettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CurrencySettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CurrencySettingsUsecase) FetchByID(c context.Context, ID string) (domain.CurrencySettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CurrencySettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CurrencySettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CurrencySettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CurrencySettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, currency_settings
func (_m *CurrencySettingsUsecase) Update(c context.Context, currency_settings *domain.CurrencySettings) error {
	ret := _m.Called(c, currency_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CurrencySettings) error); ok {
		r0 = rf(c, currency_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCurrencySettingsUsecase creates a new instance of CurrencySettingsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencySettingsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencySettingsUsecase {
	mock := &CurrencySettingsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
