// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/customers"

	mock "github.com/stretchr/testify/mock"
)

// CustomerPasswordRepository is an autogenerated mock type for the CustomerPasswordRepository type
type CustomerPasswordRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, permission_record_customer_role_mapping
func (_m *CustomerPasswordRepository) Create(c context.Context, permission_record_customer_role_mapping *domain.CustomerPassword) error {
	ret := _m.Called(c, permission_record_customer_role_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerPassword) error); ok {
		r0 = rf(c, permission_record_customer_role_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *CustomerPasswordRepository) CreateMany(c context.Context, items []domain.CustomerPassword) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.CustomerPassword) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CustomerPasswordRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CustomerPasswordRepository) Fetch(c context.Context) ([]domain.CustomerPassword, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CustomerPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CustomerPassword, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CustomerPassword); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CustomerPassword)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CustomerPasswordRepository) FetchByID(c context.Context, ID string) (domain.CustomerPassword, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CustomerPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CustomerPassword, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CustomerPassword); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CustomerPassword)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, permission_record_customer_role_mapping
func (_m *CustomerPasswordRepository) Update(c context.Context, permission_record_customer_role_mapping *domain.CustomerPassword) error {
	ret := _m.Called(c, permission_record_customer_role_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerPassword) error); ok {
		r0 = rf(c, permission_record_customer_role_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerPasswordRepository creates a new instance of CustomerPasswordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerPasswordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerPasswordRepository {
	mock := &CustomerPasswordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
