// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/customers"

	mock "github.com/stretchr/testify/mock"
)

// CustomerAttributeValueRepository is an autogenerated mock type for the CustomerAttributeValueRepository type
type CustomerAttributeValueRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, customer_attribute_value
func (_m *CustomerAttributeValueRepository) Create(c context.Context, customer_attribute_value *domain.CustomerAttributeValue) error {
	ret := _m.Called(c, customer_attribute_value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerAttributeValue) error); ok {
		r0 = rf(c, customer_attribute_value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CustomerAttributeValueRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CustomerAttributeValueRepository) Fetch(c context.Context) ([]domain.CustomerAttributeValue, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CustomerAttributeValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CustomerAttributeValue, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CustomerAttributeValue); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CustomerAttributeValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CustomerAttributeValueRepository) FetchByID(c context.Context, ID string) (domain.CustomerAttributeValue, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CustomerAttributeValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CustomerAttributeValue, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CustomerAttributeValue); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CustomerAttributeValue)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, customer_attribute_value
func (_m *CustomerAttributeValueRepository) Update(c context.Context, customer_attribute_value *domain.CustomerAttributeValue) error {
	ret := _m.Called(c, customer_attribute_value)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerAttributeValue) error); ok {
		r0 = rf(c, customer_attribute_value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerAttributeValueRepository creates a new instance of CustomerAttributeValueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerAttributeValueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerAttributeValueRepository {
	mock := &CustomerAttributeValueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
