// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/customers"

	mock "github.com/stretchr/testify/mock"
)

// CustomerAddressMappingRepository is an autogenerated mock type for the CustomerAddressMappingRepository type
type CustomerAddressMappingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, acl_record
func (_m *CustomerAddressMappingRepository) CreateMany(c context.Context, acl_record []domain.CustomerAddressMapping) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.CustomerAddressMapping) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, customer_address_mapping
func (_m *CustomerAddressMappingRepository) Create(c context.Context, customer_address_mapping *domain.CustomerAddressMapping) error {
	ret := _m.Called(c, customer_address_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerAddressMapping) error); ok {
		r0 = rf(c, customer_address_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CustomerAddressMappingRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CustomerAddressMappingRepository) Fetch(c context.Context) ([]domain.CustomerAddressMapping, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CustomerAddressMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CustomerAddressMapping, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CustomerAddressMapping); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CustomerAddressMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CustomerAddressMappingRepository) FetchByID(c context.Context, ID string) (domain.CustomerAddressMapping, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CustomerAddressMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CustomerAddressMapping, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CustomerAddressMapping); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CustomerAddressMapping)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, customer_address_mapping
func (_m *CustomerAddressMappingRepository) Update(c context.Context, customer_address_mapping *domain.CustomerAddressMapping) error {
	ret := _m.Called(c, customer_address_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerAddressMapping) error); ok {
		r0 = rf(c, customer_address_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerAddressMappingRepository creates a new instance of CustomerAddressMappingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerAddressMappingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerAddressMappingRepository {
	mock := &CustomerAddressMappingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
