// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/customers"

	mock "github.com/stretchr/testify/mock"
)

// CustomerCustomerRoleMappingRepository is an autogenerated mock type for the CustomerCustomerRoleMappingRepository type
type CustomerCustomerRoleMappingRepository struct {
	mock.Mock
}


// Create provides a mock function with given fields: c, acl_record
func (_m *CustomerCustomerRoleMappingRepository) CreateMany(c context.Context, acl_record []domain.CustomerCustomerRoleMapping) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.CustomerCustomerRoleMapping) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, customer_customer_role_mapping
func (_m *CustomerCustomerRoleMappingRepository) Create(c context.Context, customer_customer_role_mapping *domain.CustomerCustomerRoleMapping) error {
	ret := _m.Called(c, customer_customer_role_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerCustomerRoleMapping) error); ok {
		r0 = rf(c, customer_customer_role_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *CustomerCustomerRoleMappingRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *CustomerCustomerRoleMappingRepository) Fetch(c context.Context) ([]domain.CustomerCustomerRoleMapping, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.CustomerCustomerRoleMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.CustomerCustomerRoleMapping, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.CustomerCustomerRoleMapping); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CustomerCustomerRoleMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *CustomerCustomerRoleMappingRepository) FetchByID(c context.Context, ID string) (domain.CustomerCustomerRoleMapping, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.CustomerCustomerRoleMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.CustomerCustomerRoleMapping, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.CustomerCustomerRoleMapping); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.CustomerCustomerRoleMapping)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, customer_customer_role_mapping
func (_m *CustomerCustomerRoleMappingRepository) Update(c context.Context, customer_customer_role_mapping *domain.CustomerCustomerRoleMapping) error {
	ret := _m.Called(c, customer_customer_role_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CustomerCustomerRoleMapping) error); ok {
		r0 = rf(c, customer_customer_role_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerCustomerRoleMappingRepository creates a new instance of CustomerCustomerRoleMappingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerCustomerRoleMappingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerCustomerRoleMappingRepository {
	mock := &CustomerCustomerRoleMappingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
