// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/discounts"

	mock "github.com/stretchr/testify/mock"
)

// DiscountManufacturerMappingUsecase is an autogenerated mock type for the DiscountManufacturerMappingUsecase type
type DiscountManufacturerMappingUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *DiscountManufacturerMappingUsecase) CreateMany(c context.Context, acl_record []domain.DiscountManufacturerMapping) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.DiscountManufacturerMapping) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, discount_manufacturer_mapping
func (_m *DiscountManufacturerMappingUsecase) Create(c context.Context, discount_manufacturer_mapping *domain.DiscountManufacturerMapping) error {
	ret := _m.Called(c, discount_manufacturer_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DiscountManufacturerMapping) error); ok {
		r0 = rf(c, discount_manufacturer_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *DiscountManufacturerMappingUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *DiscountManufacturerMappingUsecase) Fetch(c context.Context) ([]domain.DiscountManufacturerMapping, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.DiscountManufacturerMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.DiscountManufacturerMapping, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.DiscountManufacturerMapping); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DiscountManufacturerMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, discount_manufacturer_mappingID
func (_m *DiscountManufacturerMappingUsecase) FetchByID(c context.Context, discount_manufacturer_mappingID string) (domain.DiscountManufacturerMapping, error) {
	ret := _m.Called(c, discount_manufacturer_mappingID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.DiscountManufacturerMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.DiscountManufacturerMapping, error)); ok {
		return rf(c, discount_manufacturer_mappingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.DiscountManufacturerMapping); ok {
		r0 = rf(c, discount_manufacturer_mappingID)
	} else {
		r0 = ret.Get(0).(domain.DiscountManufacturerMapping)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, discount_manufacturer_mappingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, discount_manufacturer_mapping
func (_m *DiscountManufacturerMappingUsecase) Update(c context.Context, discount_manufacturer_mapping *domain.DiscountManufacturerMapping) error {
	ret := _m.Called(c, discount_manufacturer_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DiscountManufacturerMapping) error); ok {
		r0 = rf(c, discount_manufacturer_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDiscountManufacturerMappingUsecase creates a new instance of DiscountManufacturerMappingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscountManufacturerMappingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountManufacturerMappingUsecase {
	mock := &DiscountManufacturerMappingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
