// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/discounts"

	mock "github.com/stretchr/testify/mock"
)

// DiscountUsageHistoryUsecase is an autogenerated mock type for the DiscountUsageHistoryUsecase type
type DiscountUsageHistoryUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, discount_usage_history
func (_m *DiscountUsageHistoryUsecase) Create(c context.Context, discount_usage_history *domain.DiscountUsageHistory) error {
	ret := _m.Called(c, discount_usage_history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DiscountUsageHistory) error); ok {
		r0 = rf(c, discount_usage_history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *DiscountUsageHistoryUsecase) CreateMany(c context.Context, items []domain.DiscountUsageHistory) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.DiscountUsageHistory) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *DiscountUsageHistoryUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *DiscountUsageHistoryUsecase) Fetch(c context.Context) ([]domain.DiscountUsageHistory, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.DiscountUsageHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.DiscountUsageHistory, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.DiscountUsageHistory); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DiscountUsageHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *DiscountUsageHistoryUsecase) FetchByID(c context.Context, ID string) (domain.DiscountUsageHistory, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.DiscountUsageHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.DiscountUsageHistory, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.DiscountUsageHistory); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.DiscountUsageHistory)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, discount_usage_history
func (_m *DiscountUsageHistoryUsecase) Update(c context.Context, discount_usage_history *domain.DiscountUsageHistory) error {
	ret := _m.Called(c, discount_usage_history)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DiscountUsageHistory) error); ok {
		r0 = rf(c, discount_usage_history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDiscountUsageHistoryUsecase creates a new instance of DiscountUsageHistoryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscountUsageHistoryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountUsageHistoryUsecase {
	mock := &DiscountUsageHistoryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
