// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/discounts"

	mock "github.com/stretchr/testify/mock"
)

// DiscountProductMappingRepository is an autogenerated mock type for the DiscountProductMappingRepository type
type DiscountProductMappingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, discount_product_mapping
func (_m *DiscountProductMappingRepository) Create(c context.Context, discount_product_mapping *domain.DiscountProductMapping) error {
	ret := _m.Called(c, discount_product_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DiscountProductMapping) error); ok {
		r0 = rf(c, discount_product_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *DiscountProductMappingRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *DiscountProductMappingRepository) Fetch(c context.Context) ([]domain.DiscountProductMapping, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.DiscountProductMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.DiscountProductMapping, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.DiscountProductMapping); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DiscountProductMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *DiscountProductMappingRepository) FetchByID(c context.Context, ID string) (domain.DiscountProductMapping, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.DiscountProductMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.DiscountProductMapping, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.DiscountProductMapping); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.DiscountProductMapping)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, discount_product_mapping
func (_m *DiscountProductMappingRepository) Update(c context.Context, discount_product_mapping *domain.DiscountProductMapping) error {
	ret := _m.Called(c, discount_product_mapping)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DiscountProductMapping) error); ok {
		r0 = rf(c, discount_product_mapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDiscountProductMappingRepository creates a new instance of DiscountProductMappingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscountProductMappingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountProductMappingRepository {
	mock := &DiscountProductMappingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
