// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/messages"

	mock "github.com/stretchr/testify/mock"
)

// EmailAccountSettingsRepository is an autogenerated mock type for the EmailAccountSettingsRepository type
type EmailAccountSettingsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, email_account_settings
func (_m *EmailAccountSettingsRepository) Create(c context.Context, email_account_settings *domain.EmailAccountSettings) error {
	ret := _m.Called(c, email_account_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EmailAccountSettings) error); ok {
		r0 = rf(c, email_account_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *EmailAccountSettingsRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *EmailAccountSettingsRepository) Fetch(c context.Context) ([]domain.EmailAccountSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.EmailAccountSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.EmailAccountSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.EmailAccountSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.EmailAccountSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *EmailAccountSettingsRepository) FetchByID(c context.Context, ID string) (domain.EmailAccountSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.EmailAccountSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.EmailAccountSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.EmailAccountSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.EmailAccountSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, email_account_settings
func (_m *EmailAccountSettingsRepository) Update(c context.Context, email_account_settings *domain.EmailAccountSettings) error {
	ret := _m.Called(c, email_account_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EmailAccountSettings) error); ok {
		r0 = rf(c, email_account_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailAccountSettingsRepository creates a new instance of EmailAccountSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailAccountSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailAccountSettingsRepository {
	mock := &EmailAccountSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
