// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/messages"

	mock "github.com/stretchr/testify/mock"
)

// EmailAccountUsecase is an autogenerated mock type for the EmailAccountUsecase type
type EmailAccountUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, email_account
func (_m *EmailAccountUsecase) Create(c context.Context, email_account *domain.EmailAccount) error {
	ret := _m.Called(c, email_account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EmailAccount) error); ok {
		r0 = rf(c, email_account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *EmailAccountUsecase) CreateMany(c context.Context, items []domain.EmailAccount) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.EmailAccount) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *EmailAccountUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *EmailAccountUsecase) Fetch(c context.Context) ([]domain.EmailAccount, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.EmailAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.EmailAccount, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.EmailAccount); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.EmailAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *EmailAccountUsecase) FetchByID(c context.Context, ID string) (domain.EmailAccount, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.EmailAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.EmailAccount, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.EmailAccount); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.EmailAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, email_account
func (_m *EmailAccountUsecase) Update(c context.Context, email_account *domain.EmailAccount) error {
	ret := _m.Called(c, email_account)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EmailAccount) error); ok {
		r0 = rf(c, email_account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailAccountUsecase creates a new instance of EmailAccountUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailAccountUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailAccountUsecase {
	mock := &EmailAccountUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
