// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/forums"

	mock "github.com/stretchr/testify/mock"
)

// ForumSubscriptionRepository is an autogenerated mock type for the ForumSubscriptionRepository type
type ForumSubscriptionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, forum_subscription
func (_m *ForumSubscriptionRepository) Create(c context.Context, forum_subscription *domain.ForumSubscription) error {
	ret := _m.Called(c, forum_subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ForumSubscription) error); ok {
		r0 = rf(c, forum_subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ForumSubscriptionRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ForumSubscriptionRepository) Fetch(c context.Context) ([]domain.ForumSubscription, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ForumSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ForumSubscription, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ForumSubscription); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ForumSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ForumSubscriptionRepository) FetchByID(c context.Context, ID string) (domain.ForumSubscription, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ForumSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ForumSubscription, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ForumSubscription); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ForumSubscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, forum_subscription
func (_m *ForumSubscriptionRepository) Update(c context.Context, forum_subscription *domain.ForumSubscription) error {
	ret := _m.Called(c, forum_subscription)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ForumSubscription) error); ok {
		r0 = rf(c, forum_subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewForumSubscriptionRepository creates a new instance of ForumSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForumSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForumSubscriptionRepository {
	mock := &ForumSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
