// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/forums"

	mock "github.com/stretchr/testify/mock"
)

// ForumPostRepository is an autogenerated mock type for the ForumPostRepository type
type ForumPostRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *ForumPostRepository) CreateMany(c context.Context, acl_record []domain.ForumPost) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ForumPost) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, forum_post
func (_m *ForumPostRepository) Create(c context.Context, forum_post *domain.ForumPost) error {
	ret := _m.Called(c, forum_post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ForumPost) error); ok {
		r0 = rf(c, forum_post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ForumPostRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ForumPostRepository) Fetch(c context.Context) ([]domain.ForumPost, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ForumPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ForumPost, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ForumPost); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ForumPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ForumPostRepository) FetchByID(c context.Context, ID string) (domain.ForumPost, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ForumPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ForumPost, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ForumPost); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ForumPost)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, forum_post
func (_m *ForumPostRepository) Update(c context.Context, forum_post *domain.ForumPost) error {
	ret := _m.Called(c, forum_post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ForumPost) error); ok {
		r0 = rf(c, forum_post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewForumPostRepository creates a new instance of ForumPostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForumPostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForumPostRepository {
	mock := &ForumPostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
