// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/forums"

	mock "github.com/stretchr/testify/mock"
)

// ForumGroupUsecase is an autogenerated mock type for the ForumGroupUsecase type
type ForumGroupUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, forum_group
func (_m *ForumGroupUsecase) Create(c context.Context, forum_group *domain.ForumGroup) error {
	ret := _m.Called(c, forum_group)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ForumGroup) error); ok {
		r0 = rf(c, forum_group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ForumGroupUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ForumGroupUsecase) Fetch(c context.Context) ([]domain.ForumGroup, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ForumGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ForumGroup, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ForumGroup); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ForumGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ForumGroupUsecase) FetchByID(c context.Context, ID string) (domain.ForumGroup, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ForumGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ForumGroup, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ForumGroup); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ForumGroup)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, forum_group
func (_m *ForumGroupUsecase) Update(c context.Context, forum_group *domain.ForumGroup) error {
	ret := _m.Called(c, forum_group)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ForumGroup) error); ok {
		r0 = rf(c, forum_group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewForumGroupUsecase creates a new instance of ForumGroupUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForumGroupUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForumGroupUsecase {
	mock := &ForumGroupUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
