// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/gdpr"

	mock "github.com/stretchr/testify/mock"
)

// GdprSettingsRepository is an autogenerated mock type for the GdprSettingsRepository type
type GdprSettingsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *GdprSettingsRepository) CreateMany(c context.Context, acl_record []domain.GdprSettings) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.GdprSettings) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, gdpr_settings
func (_m *GdprSettingsRepository) Create(c context.Context, gdpr_settings *domain.GdprSettings) error {
	ret := _m.Called(c, gdpr_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GdprSettings) error); ok {
		r0 = rf(c, gdpr_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *GdprSettingsRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *GdprSettingsRepository) Fetch(c context.Context) ([]domain.GdprSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.GdprSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.GdprSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.GdprSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GdprSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *GdprSettingsRepository) FetchByID(c context.Context, ID string) (domain.GdprSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.GdprSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.GdprSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.GdprSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.GdprSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, gdpr_settings
func (_m *GdprSettingsRepository) Update(c context.Context, gdpr_settings *domain.GdprSettings) error {
	ret := _m.Called(c, gdpr_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GdprSettings) error); ok {
		r0 = rf(c, gdpr_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGdprSettingsRepository creates a new instance of GdprSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGdprSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GdprSettingsRepository {
	mock := &GdprSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
