// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/common"

	mock "github.com/stretchr/testify/mock"
)

// GenericAttributeRepository is an autogenerated mock type for the GenericAttributeRepository type
type GenericAttributeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *GenericAttributeRepository) CreateMany(c context.Context, acl_record []domain.GenericAttribute) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.GenericAttribute) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, generic_attribute
func (_m *GenericAttributeRepository) Create(c context.Context, generic_attribute *domain.GenericAttribute) error {
	ret := _m.Called(c, generic_attribute)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GenericAttribute) error); ok {
		r0 = rf(c, generic_attribute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *GenericAttributeRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *GenericAttributeRepository) Fetch(c context.Context) ([]domain.GenericAttribute, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.GenericAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.GenericAttribute, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.GenericAttribute); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GenericAttribute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *GenericAttributeRepository) FetchByID(c context.Context, ID string) (domain.GenericAttribute, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.GenericAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.GenericAttribute, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.GenericAttribute); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.GenericAttribute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, generic_attribute
func (_m *GenericAttributeRepository) Update(c context.Context, generic_attribute *domain.GenericAttribute) error {
	ret := _m.Called(c, generic_attribute)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GenericAttribute) error); ok {
		r0 = rf(c, generic_attribute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGenericAttributeRepository creates a new instance of GenericAttributeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenericAttributeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenericAttributeRepository {
	mock := &GenericAttributeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
