// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/orders"

	mock "github.com/stretchr/testify/mock"
)

// GiftCardUsageHistoryRepository is an autogenerated mock type for the GiftCardUsageHistoryRepository type
type GiftCardUsageHistoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, gift_card_usage_history
func (_m *GiftCardUsageHistoryRepository) Create(c context.Context, gift_card_usage_history *domain.GiftCardUsageHistory) error {
	ret := _m.Called(c, gift_card_usage_history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GiftCardUsageHistory) error); ok {
		r0 = rf(c, gift_card_usage_history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *GiftCardUsageHistoryRepository) CreateMany(c context.Context, items []domain.GiftCardUsageHistory) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.GiftCardUsageHistory) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *GiftCardUsageHistoryRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *GiftCardUsageHistoryRepository) Fetch(c context.Context) ([]domain.GiftCardUsageHistory, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.GiftCardUsageHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.GiftCardUsageHistory, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.GiftCardUsageHistory); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GiftCardUsageHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *GiftCardUsageHistoryRepository) FetchByID(c context.Context, ID string) (domain.GiftCardUsageHistory, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.GiftCardUsageHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.GiftCardUsageHistory, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.GiftCardUsageHistory); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.GiftCardUsageHistory)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, gift_card_usage_history
func (_m *GiftCardUsageHistoryRepository) Update(c context.Context, gift_card_usage_history *domain.GiftCardUsageHistory) error {
	ret := _m.Called(c, gift_card_usage_history)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GiftCardUsageHistory) error); ok {
		r0 = rf(c, gift_card_usage_history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGiftCardUsageHistoryRepository creates a new instance of GiftCardUsageHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGiftCardUsageHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GiftCardUsageHistoryRepository {
	mock := &GiftCardUsageHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
