// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAclSupported is an autogenerated mock type for the IAclSupported type
type IAclSupported struct {
	mock.Mock
}

// GetSubjectToAcl provides a mock function with no fields
func (_m *IAclSupported) GetSubjectToAcl() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSubjectToAcl")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetSubjectToAcl provides a mock function with given fields: subjectToAcl
func (_m *IAclSupported) SetSubjectToAcl(subjectToAcl bool) {
	_m.Called(subjectToAcl)
}

// NewIAclSupported creates a new instance of IAclSupported. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAclSupported(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAclSupported {
	mock := &IAclSupported{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
