// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ILocalizedEntity is an autogenerated mock type for the ILocalizedEntity type
type ILocalizedEntity struct {
	mock.Mock
}

// NewILocalizedEntity creates a new instance of ILocalizedEntity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILocalizedEntity(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILocalizedEntity {
	mock := &ILocalizedEntity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
