// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IStoreMappingSupported is an autogenerated mock type for the IStoreMappingSupported type
type IStoreMappingSupported struct {
	mock.Mock
}

// GetLimitedToStores provides a mock function with no fields
func (_m *IStoreMappingSupported) GetLimitedToStores() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLimitedToStores")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetLimitedToStores provides a mock function with given fields: limitedToStores
func (_m *IStoreMappingSupported) SetLimitedToStores(limitedToStores bool) {
	_m.Called(limitedToStores)
}

// NewIStoreMappingSupported creates a new instance of IStoreMappingSupported. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStoreMappingSupported(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStoreMappingSupported {
	mock := &IStoreMappingSupported{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
