// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/localization"

	mock "github.com/stretchr/testify/mock"
)

// LocalizationSettingsUsecase is an autogenerated mock type for the LocalizationSettingsUsecase type
type LocalizationSettingsUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, localization_settings
func (_m *LocalizationSettingsUsecase) Create(c context.Context, localization_settings *domain.LocalizationSettings) error {
	ret := _m.Called(c, localization_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.LocalizationSettings) error); ok {
		r0 = rf(c, localization_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *LocalizationSettingsUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *LocalizationSettingsUsecase) Fetch(c context.Context) ([]domain.LocalizationSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.LocalizationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.LocalizationSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.LocalizationSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LocalizationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *LocalizationSettingsUsecase) FetchByID(c context.Context, ID string) (domain.LocalizationSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.LocalizationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.LocalizationSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.LocalizationSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.LocalizationSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, localization_settings
func (_m *LocalizationSettingsUsecase) Update(c context.Context, localization_settings *domain.LocalizationSettings) error {
	ret := _m.Called(c, localization_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.LocalizationSettings) error); ok {
		r0 = rf(c, localization_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLocalizationSettingsUsecase creates a new instance of LocalizationSettingsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalizationSettingsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalizationSettingsUsecase {
	mock := &LocalizationSettingsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
