// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/media"

	mock "github.com/stretchr/testify/mock"
)

// MediaSettingsRepository is an autogenerated mock type for the MediaSettingsRepository type
type MediaSettingsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, media_settings
func (_m *MediaSettingsRepository) Create(c context.Context, media_settings *domain.MediaSettings) error {
	ret := _m.Called(c, media_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MediaSettings) error); ok {
		r0 = rf(c, media_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *MediaSettingsRepository) CreateMany(c context.Context, items []domain.MediaSettings) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.MediaSettings) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *MediaSettingsRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *MediaSettingsRepository) Fetch(c context.Context) ([]domain.MediaSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.MediaSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.MediaSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.MediaSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MediaSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *MediaSettingsRepository) FetchByID(c context.Context, ID string) (domain.MediaSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.MediaSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MediaSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MediaSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.MediaSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, media_settings
func (_m *MediaSettingsRepository) Update(c context.Context, media_settings *domain.MediaSettings) error {
	ret := _m.Called(c, media_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MediaSettings) error); ok {
		r0 = rf(c, media_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMediaSettingsRepository creates a new instance of MediaSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaSettingsRepository {
	mock := &MediaSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
