// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/messages"

	mock "github.com/stretchr/testify/mock"
)

// MessageTemplateRepository is an autogenerated mock type for the MessageTemplateRepository type
type MessageTemplateRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, message_template
func (_m *MessageTemplateRepository) Create(c context.Context, message_template *domain.MessageTemplate) error {
	ret := _m.Called(c, message_template)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MessageTemplate) error); ok {
		r0 = rf(c, message_template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *MessageTemplateRepository) CreateMany(c context.Context, items []domain.MessageTemplate) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.MessageTemplate) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *MessageTemplateRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *MessageTemplateRepository) Fetch(c context.Context) ([]domain.MessageTemplate, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.MessageTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.MessageTemplate, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.MessageTemplate); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessageTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *MessageTemplateRepository) FetchByID(c context.Context, ID string) (domain.MessageTemplate, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.MessageTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MessageTemplate, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MessageTemplate); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.MessageTemplate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, message_template
func (_m *MessageTemplateRepository) Update(c context.Context, message_template *domain.MessageTemplate) error {
	ret := _m.Called(c, message_template)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MessageTemplate) error); ok {
		r0 = rf(c, message_template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessageTemplateRepository creates a new instance of MessageTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageTemplateRepository {
	mock := &MessageTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
