// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/messages"

	mock "github.com/stretchr/testify/mock"
)

// MessagesSettingsUsecase is an autogenerated mock type for the MessagesSettingsUsecase type
type MessagesSettingsUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *MessagesSettingsUsecase) CreateMany(c context.Context, acl_record []domain.MessagesSettings) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.MessagesSettings) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, messages_settings
func (_m *MessagesSettingsUsecase) Create(c context.Context, messages_settings *domain.MessagesSettings) error {
	ret := _m.Called(c, messages_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MessagesSettings) error); ok {
		r0 = rf(c, messages_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *MessagesSettingsUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *MessagesSettingsUsecase) Fetch(c context.Context) ([]domain.MessagesSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.MessagesSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.MessagesSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.MessagesSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessagesSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *MessagesSettingsUsecase) FetchByID(c context.Context, ID string) (domain.MessagesSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.MessagesSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MessagesSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MessagesSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.MessagesSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, messages_settings
func (_m *MessagesSettingsUsecase) Update(c context.Context, messages_settings *domain.MessagesSettings) error {
	ret := _m.Called(c, messages_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MessagesSettings) error); ok {
		r0 = rf(c, messages_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessagesSettingsUsecase creates a new instance of MessagesSettingsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagesSettingsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagesSettingsUsecase {
	mock := &MessagesSettingsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
