// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/news"

	mock "github.com/stretchr/testify/mock"
)

// NewsCommentUsecase is an autogenerated mock type for the NewsCommentUsecase type
type NewsCommentUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, news_comment
func (_m *NewsCommentUsecase) Create(c context.Context, news_comment *domain.NewsComment) error {
	ret := _m.Called(c, news_comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NewsComment) error); ok {
		r0 = rf(c, news_comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *NewsCommentUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *NewsCommentUsecase) Fetch(c context.Context) ([]domain.NewsComment, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.NewsComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.NewsComment, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.NewsComment); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NewsComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *NewsCommentUsecase) FetchByID(c context.Context, ID string) (domain.NewsComment, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.NewsComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.NewsComment, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.NewsComment); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.NewsComment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, news_comment
func (_m *NewsCommentUsecase) Update(c context.Context, news_comment *domain.NewsComment) error {
	ret := _m.Called(c, news_comment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NewsComment) error); ok {
		r0 = rf(c, news_comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNewsCommentUsecase creates a new instance of NewsCommentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNewsCommentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *NewsCommentUsecase {
	mock := &NewsCommentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
