// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/orders"

	mock "github.com/stretchr/testify/mock"
)

// OrderNoteRepository is an autogenerated mock type for the OrderNoteRepository type
type OrderNoteRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, order_note
func (_m *OrderNoteRepository) Create(c context.Context, order_note *domain.OrderNote) error {
	ret := _m.Called(c, order_note)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OrderNote) error); ok {
		r0 = rf(c, order_note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *OrderNoteRepository) CreateMany(c context.Context, items []domain.OrderNote) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.OrderNote) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *OrderNoteRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *OrderNoteRepository) Fetch(c context.Context) ([]domain.OrderNote, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.OrderNote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.OrderNote, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.OrderNote); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OrderNote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *OrderNoteRepository) FetchByID(c context.Context, ID string) (domain.OrderNote, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.OrderNote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.OrderNote, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.OrderNote); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.OrderNote)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, order_note
func (_m *OrderNoteRepository) Update(c context.Context, order_note *domain.OrderNote) error {
	ret := _m.Called(c, order_note)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OrderNote) error); ok {
		r0 = rf(c, order_note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderNoteRepository creates a new instance of OrderNoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderNoteRepository {
	mock := &OrderNoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
