// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/media"

	mock "github.com/stretchr/testify/mock"
)

// PictureRepository is an autogenerated mock type for the PictureRepository type
type PictureRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, picture
func (_m *PictureRepository) Create(c context.Context, picture *domain.Picture) error {
	ret := _m.Called(c, picture)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Picture) error); ok {
		r0 = rf(c, picture)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *PictureRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *PictureRepository) Fetch(c context.Context) ([]domain.Picture, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Picture
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Picture, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Picture); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Picture)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *PictureRepository) FetchByID(c context.Context, ID string) (domain.Picture, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.Picture
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Picture, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Picture); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.Picture)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, picture
func (_m *PictureRepository) Update(c context.Context, picture *domain.Picture) error {
	ret := _m.Called(c, picture)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Picture) error); ok {
		r0 = rf(c, picture)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPictureRepository creates a new instance of PictureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPictureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PictureRepository {
	mock := &PictureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
