// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/media"

	mock "github.com/stretchr/testify/mock"
)

// PictureBinaryUsecase is an autogenerated mock type for the PictureBinaryUsecase type
type PictureBinaryUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, picture_binary
func (_m *PictureBinaryUsecase) Create(c context.Context, picture_binary *domain.PictureBinary) error {
	ret := _m.Called(c, picture_binary)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PictureBinary) error); ok {
		r0 = rf(c, picture_binary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *PictureBinaryUsecase) CreateMany(c context.Context, items []domain.PictureBinary) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.PictureBinary) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *PictureBinaryUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *PictureBinaryUsecase) Fetch(c context.Context) ([]domain.PictureBinary, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.PictureBinary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.PictureBinary, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.PictureBinary); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PictureBinary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *PictureBinaryUsecase) FetchByID(c context.Context, ID string) (domain.PictureBinary, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.PictureBinary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.PictureBinary, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.PictureBinary); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.PictureBinary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, picture_binary
func (_m *PictureBinaryUsecase) Update(c context.Context, picture_binary *domain.PictureBinary) error {
	ret := _m.Called(c, picture_binary)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PictureBinary) error); ok {
		r0 = rf(c, picture_binary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPictureBinaryUsecase creates a new instance of PictureBinaryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPictureBinaryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PictureBinaryUsecase {
	mock := &PictureBinaryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
