// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/polls"

	mock "github.com/stretchr/testify/mock"
)

// PollVotingRecordRepository is an autogenerated mock type for the PollVotingRecordRepository type
type PollVotingRecordRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *PollVotingRecordRepository) CreateMany(c context.Context, acl_record []domain.PollVotingRecord) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.PollVotingRecord) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, poll_voting_record
func (_m *PollVotingRecordRepository) Create(c context.Context, poll_voting_record *domain.PollVotingRecord) error {
	ret := _m.Called(c, poll_voting_record)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PollVotingRecord) error); ok {
		r0 = rf(c, poll_voting_record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *PollVotingRecordRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *PollVotingRecordRepository) Fetch(c context.Context) ([]domain.PollVotingRecord, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.PollVotingRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.PollVotingRecord, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.PollVotingRecord); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PollVotingRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *PollVotingRecordRepository) FetchByID(c context.Context, ID string) (domain.PollVotingRecord, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.PollVotingRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.PollVotingRecord, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.PollVotingRecord); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.PollVotingRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, poll_voting_record
func (_m *PollVotingRecordRepository) Update(c context.Context, poll_voting_record *domain.PollVotingRecord) error {
	ret := _m.Called(c, poll_voting_record)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PollVotingRecord) error); ok {
		r0 = rf(c, poll_voting_record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPollVotingRecordRepository creates a new instance of PollVotingRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPollVotingRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PollVotingRecordRepository {
	mock := &PollVotingRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
