// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/forums"

	mock "github.com/stretchr/testify/mock"
)

// PrivateMessageRepository is an autogenerated mock type for the PrivateMessageRepository type
type PrivateMessageRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, private_message
func (_m *PrivateMessageRepository) Create(c context.Context, private_message *domain.PrivateMessage) error {
	ret := _m.Called(c, private_message)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PrivateMessage) error); ok {
		r0 = rf(c, private_message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *PrivateMessageRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *PrivateMessageRepository) Fetch(c context.Context) ([]domain.PrivateMessage, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.PrivateMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.PrivateMessage, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.PrivateMessage); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PrivateMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *PrivateMessageRepository) FetchByID(c context.Context, ID string) (domain.PrivateMessage, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.PrivateMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.PrivateMessage, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.PrivateMessage); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.PrivateMessage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, private_message
func (_m *PrivateMessageRepository) Update(c context.Context, private_message *domain.PrivateMessage) error {
	ret := _m.Called(c, private_message)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PrivateMessage) error); ok {
		r0 = rf(c, private_message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPrivateMessageRepository creates a new instance of PrivateMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrivateMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrivateMessageRepository {
	mock := &PrivateMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
