// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ProductAttributeCombinationPictureRepository is an autogenerated mock type for the ProductAttributeCombinationPictureRepository type
type ProductAttributeCombinationPictureRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, product_attribute_combination_picture
func (_m *ProductAttributeCombinationPictureRepository) Create(c context.Context, product_attribute_combination_picture *domain.ProductAttributeCombinationPicture) error {
	ret := _m.Called(c, product_attribute_combination_picture)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductAttributeCombinationPicture) error); ok {
		r0 = rf(c, product_attribute_combination_picture)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *ProductAttributeCombinationPictureRepository) CreateMany(c context.Context, items []domain.ProductAttributeCombinationPicture) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ProductAttributeCombinationPicture) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ProductAttributeCombinationPictureRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ProductAttributeCombinationPictureRepository) Fetch(c context.Context) ([]domain.ProductAttributeCombinationPicture, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ProductAttributeCombinationPicture
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProductAttributeCombinationPicture, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProductAttributeCombinationPicture); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductAttributeCombinationPicture)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ProductAttributeCombinationPictureRepository) FetchByID(c context.Context, ID string) (domain.ProductAttributeCombinationPicture, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ProductAttributeCombinationPicture
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ProductAttributeCombinationPicture, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ProductAttributeCombinationPicture); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ProductAttributeCombinationPicture)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, product_attribute_combination_picture
func (_m *ProductAttributeCombinationPictureRepository) Update(c context.Context, product_attribute_combination_picture *domain.ProductAttributeCombinationPicture) error {
	ret := _m.Called(c, product_attribute_combination_picture)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductAttributeCombinationPicture) error); ok {
		r0 = rf(c, product_attribute_combination_picture)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductAttributeCombinationPictureRepository creates a new instance of ProductAttributeCombinationPictureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductAttributeCombinationPictureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductAttributeCombinationPictureRepository {
	mock := &ProductAttributeCombinationPictureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
