// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ProductEditorSettingsRepository is an autogenerated mock type for the ProductEditorSettingsRepository type
type ProductEditorSettingsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *ProductEditorSettingsRepository) CreateMany(c context.Context, acl_record []domain.ProductEditorSettings) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ProductEditorSettings) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, product_editor_settings
func (_m *ProductEditorSettingsRepository) Create(c context.Context, product_editor_settings *domain.ProductEditorSettings) error {
	ret := _m.Called(c, product_editor_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductEditorSettings) error); ok {
		r0 = rf(c, product_editor_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ProductEditorSettingsRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ProductEditorSettingsRepository) Fetch(c context.Context) ([]domain.ProductEditorSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ProductEditorSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProductEditorSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProductEditorSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductEditorSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ProductEditorSettingsRepository) FetchByID(c context.Context, ID string) (domain.ProductEditorSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ProductEditorSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ProductEditorSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ProductEditorSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ProductEditorSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, product_editor_settings
func (_m *ProductEditorSettingsRepository) Update(c context.Context, product_editor_settings *domain.ProductEditorSettings) error {
	ret := _m.Called(c, product_editor_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductEditorSettings) error); ok {
		r0 = rf(c, product_editor_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductEditorSettingsRepository creates a new instance of ProductEditorSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductEditorSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductEditorSettingsRepository {
	mock := &ProductEditorSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
