// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ProductWarehouseInventoryRepository is an autogenerated mock type for the ProductWarehouseInventoryRepository type
type ProductWarehouseInventoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, product_inventory_warehouse
func (_m *ProductWarehouseInventoryRepository) Create(c context.Context, product_inventory_warehouse *domain.ProductWarehouseInventory) error {
	ret := _m.Called(c, product_inventory_warehouse)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductWarehouseInventory) error); ok {
		r0 = rf(c, product_inventory_warehouse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *ProductWarehouseInventoryRepository) CreateMany(c context.Context, items []domain.ProductWarehouseInventory) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ProductWarehouseInventory) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ProductWarehouseInventoryRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ProductWarehouseInventoryRepository) Fetch(c context.Context) ([]domain.ProductWarehouseInventory, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ProductWarehouseInventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProductWarehouseInventory, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProductWarehouseInventory); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductWarehouseInventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ProductWarehouseInventoryRepository) FetchByID(c context.Context, ID string) (domain.ProductWarehouseInventory, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ProductWarehouseInventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ProductWarehouseInventory, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ProductWarehouseInventory); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ProductWarehouseInventory)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, product_inventory_warehouse
func (_m *ProductWarehouseInventoryRepository) Update(c context.Context, product_inventory_warehouse *domain.ProductWarehouseInventory) error {
	ret := _m.Called(c, product_inventory_warehouse)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductWarehouseInventory) error); ok {
		r0 = rf(c, product_inventory_warehouse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductWarehouseInventoryRepository creates a new instance of ProductWarehouseInventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductWarehouseInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductWarehouseInventoryRepository {
	mock := &ProductWarehouseInventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
