// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ProductTemplateRepository is an autogenerated mock type for the ProductTemplateRepository type
type ProductTemplateRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *ProductTemplateRepository) CreateMany(c context.Context, acl_record []domain.ProductTemplate) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ProductTemplate) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, product_template
func (_m *ProductTemplateRepository) Create(c context.Context, product_template *domain.ProductTemplate) error {
	ret := _m.Called(c, product_template)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductTemplate) error); ok {
		r0 = rf(c, product_template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ProductTemplateRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ProductTemplateRepository) Fetch(c context.Context) ([]domain.ProductTemplate, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ProductTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProductTemplate, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProductTemplate); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ProductTemplateRepository) FetchByID(c context.Context, ID string) (domain.ProductTemplate, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ProductTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ProductTemplate, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ProductTemplate); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ProductTemplate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, product_template
func (_m *ProductTemplateRepository) Update(c context.Context, product_template *domain.ProductTemplate) error {
	ret := _m.Called(c, product_template)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductTemplate) error); ok {
		r0 = rf(c, product_template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductTemplateRepository creates a new instance of ProductTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductTemplateRepository {
	mock := &ProductTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
