// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ProductVideoUsecase is an autogenerated mock type for the ProductVideoUsecase type
type ProductVideoUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, product_video
func (_m *ProductVideoUsecase) Create(c context.Context, product_video *domain.ProductVideo) error {
	ret := _m.Called(c, product_video)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductVideo) error); ok {
		r0 = rf(c, product_video)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *ProductVideoUsecase) CreateMany(c context.Context, items []domain.ProductVideo) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ProductVideo) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ProductVideoUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ProductVideoUsecase) Fetch(c context.Context) ([]domain.ProductVideo, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ProductVideo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProductVideo, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProductVideo); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductVideo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ProductVideoUsecase) FetchByID(c context.Context, ID string) (domain.ProductVideo, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ProductVideo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ProductVideo, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ProductVideo); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ProductVideo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, product_video
func (_m *ProductVideoUsecase) Update(c context.Context, product_video *domain.ProductVideo) error {
	ret := _m.Called(c, product_video)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductVideo) error); ok {
		r0 = rf(c, product_video)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductVideoUsecase creates a new instance of ProductVideoUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductVideoUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductVideoUsecase {
	mock := &ProductVideoUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
