// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ProductAttributeRepository is an autogenerated mock type for the ProductAttributeRepository type
type ProductAttributeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *ProductAttributeRepository) CreateMany(c context.Context, acl_record []domain.ProductAttribute) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ProductAttribute) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, product_attribute
func (_m *ProductAttributeRepository) Create(c context.Context, product_attribute *domain.ProductAttribute) error {
	ret := _m.Called(c, product_attribute)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductAttribute) error); ok {
		r0 = rf(c, product_attribute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ProductAttributeRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ProductAttributeRepository) Fetch(c context.Context) ([]domain.ProductAttribute, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ProductAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProductAttribute, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProductAttribute); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductAttribute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ProductAttributeRepository) FetchByID(c context.Context, ID string) (domain.ProductAttribute, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ProductAttribute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ProductAttribute, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ProductAttribute); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ProductAttribute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, product_attribute
func (_m *ProductAttributeRepository) Update(c context.Context, product_attribute *domain.ProductAttribute) error {
	ret := _m.Called(c, product_attribute)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductAttribute) error); ok {
		r0 = rf(c, product_attribute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductAttributeRepository creates a new instance of ProductAttributeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductAttributeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductAttributeRepository {
	mock := &ProductAttributeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
