// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ProductManufacturerUsecase is an autogenerated mock type for the ProductManufacturerUsecase type
type ProductManufacturerUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, product_manufacturer
func (_m *ProductManufacturerUsecase) Create(c context.Context, product_manufacturer *domain.ProductManufacturer) error {
	ret := _m.Called(c, product_manufacturer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductManufacturer) error); ok {
		r0 = rf(c, product_manufacturer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ProductManufacturerUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ProductManufacturerUsecase) Fetch(c context.Context) ([]domain.ProductManufacturer, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ProductManufacturer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProductManufacturer, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProductManufacturer); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductManufacturer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ProductManufacturerUsecase) FetchByID(c context.Context, ID string) (domain.ProductManufacturer, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ProductManufacturer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ProductManufacturer, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ProductManufacturer); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ProductManufacturer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, product_manufacturer
func (_m *ProductManufacturerUsecase) Update(c context.Context, product_manufacturer *domain.ProductManufacturer) error {
	ret := _m.Called(c, product_manufacturer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductManufacturer) error); ok {
		r0 = rf(c, product_manufacturer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductManufacturerUsecase creates a new instance of ProductManufacturerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductManufacturerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductManufacturerUsecase {
	mock := &ProductManufacturerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
