// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/messages"

	mock "github.com/stretchr/testify/mock"
)

// QueuedEmailUsecase is an autogenerated mock type for the QueuedEmailUsecase type
type QueuedEmailUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, queued_email
func (_m *QueuedEmailUsecase) Create(c context.Context, queued_email *domain.QueuedEmail) error {
	ret := _m.Called(c, queued_email)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.QueuedEmail) error); ok {
		r0 = rf(c, queued_email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *QueuedEmailUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *QueuedEmailUsecase) Fetch(c context.Context) ([]domain.QueuedEmail, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.QueuedEmail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.QueuedEmail, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.QueuedEmail); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.QueuedEmail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *QueuedEmailUsecase) FetchByID(c context.Context, ID string) (domain.QueuedEmail, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.QueuedEmail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.QueuedEmail, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.QueuedEmail); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.QueuedEmail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, queued_email
func (_m *QueuedEmailUsecase) Update(c context.Context, queued_email *domain.QueuedEmail) error {
	ret := _m.Called(c, queued_email)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.QueuedEmail) error); ok {
		r0 = rf(c, queued_email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQueuedEmailUsecase creates a new instance of QueuedEmailUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueuedEmailUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueuedEmailUsecase {
	mock := &QueuedEmailUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
