// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/orders"

	mock "github.com/stretchr/testify/mock"
)

// ReturnRequestRepository is an autogenerated mock type for the ReturnRequestRepository type
type ReturnRequestRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields
func (_m *ReturnRequestRepository) CreateMany(c context.Context, acl_record []domain.ReturnRequest) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.ReturnRequest) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, return_request
func (_m *ReturnRequestRepository) Create(c context.Context, return_request *domain.ReturnRequest) error {
	ret := _m.Called(c, return_request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReturnRequest) error); ok {
		r0 = rf(c, return_request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ReturnRequestRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ReturnRequestRepository) Fetch(c context.Context) ([]domain.ReturnRequest, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ReturnRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ReturnRequest, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ReturnRequest); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReturnRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ReturnRequestRepository) FetchByID(c context.Context, ID string) (domain.ReturnRequest, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ReturnRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ReturnRequest, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ReturnRequest); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ReturnRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, return_request
func (_m *ReturnRequestRepository) Update(c context.Context, return_request *domain.ReturnRequest) error {
	ret := _m.Called(c, return_request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReturnRequest) error); ok {
		r0 = rf(c, return_request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReturnRequestRepository creates a new instance of ReturnRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReturnRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReturnRequestRepository {
	mock := &ReturnRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
