// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/common"

	mock "github.com/stretchr/testify/mock"
)

// SearchTermReportLineRepository is an autogenerated mock type for the SearchTermReportLineRepository type
type SearchTermReportLineRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, search_term_record_line
func (_m *SearchTermReportLineRepository) Create(c context.Context, search_term_record_line *domain.SearchTermReportLine) error {
	ret := _m.Called(c, search_term_record_line)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchTermReportLine) error); ok {
		r0 = rf(c, search_term_record_line)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *SearchTermReportLineRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *SearchTermReportLineRepository) Fetch(c context.Context) ([]domain.SearchTermReportLine, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.SearchTermReportLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.SearchTermReportLine, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.SearchTermReportLine); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SearchTermReportLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *SearchTermReportLineRepository) FetchByID(c context.Context, ID string) (domain.SearchTermReportLine, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.SearchTermReportLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.SearchTermReportLine, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.SearchTermReportLine); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.SearchTermReportLine)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, search_term_record_line
func (_m *SearchTermReportLineRepository) Update(c context.Context, search_term_record_line *domain.SearchTermReportLine) error {
	ret := _m.Called(c, search_term_record_line)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchTermReportLine) error); ok {
		r0 = rf(c, search_term_record_line)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSearchTermReportLineRepository creates a new instance of SearchTermReportLineRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchTermReportLineRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchTermReportLineRepository {
	mock := &SearchTermReportLineRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
