// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/common"

	mock "github.com/stretchr/testify/mock"
)

// SearchTermUsecase is an autogenerated mock type for the SearchTermUsecase type
type SearchTermUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, search_term
func (_m *SearchTermUsecase) Create(c context.Context, search_term *domain.SearchTerm) error {
	ret := _m.Called(c, search_term)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchTerm) error); ok {
		r0 = rf(c, search_term)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *SearchTermUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *SearchTermUsecase) Fetch(c context.Context) ([]domain.SearchTerm, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.SearchTerm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.SearchTerm, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.SearchTerm); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SearchTerm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *SearchTermUsecase) FetchByID(c context.Context, ID string) (domain.SearchTerm, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.SearchTerm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.SearchTerm, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.SearchTerm); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.SearchTerm)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, search_term
func (_m *SearchTermUsecase) Update(c context.Context, search_term *domain.SearchTerm) error {
	ret := _m.Called(c, search_term)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchTerm) error); ok {
		r0 = rf(c, search_term)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSearchTermUsecase creates a new instance of SearchTermUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchTermUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchTermUsecase {
	mock := &SearchTermUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
