// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/shipping"

	mock "github.com/stretchr/testify/mock"
)

// ShipmentUsecase is an autogenerated mock type for the ShipmentUsecase type
type ShipmentUsecase struct {
	mock.Mock
}

func (_m *ShipmentUsecase) CreateMany(c context.Context, acl_record []domain.Shipment) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Shipment) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, shipment
func (_m *ShipmentUsecase) Create(c context.Context, shipment *domain.Shipment) error {
	ret := _m.Called(c, shipment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Shipment) error); ok {
		r0 = rf(c, shipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ShipmentUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ShipmentUsecase) Fetch(c context.Context) ([]domain.Shipment, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Shipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Shipment, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Shipment); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Shipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ShipmentUsecase) FetchByID(c context.Context, ID string) (domain.Shipment, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.Shipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Shipment, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Shipment); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.Shipment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, shipment
func (_m *ShipmentUsecase) Update(c context.Context, shipment *domain.Shipment) error {
	ret := _m.Called(c, shipment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Shipment) error); ok {
		r0 = rf(c, shipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShipmentUsecase creates a new instance of ShipmentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipmentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipmentUsecase {
	mock := &ShipmentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
