// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/shipping"

	mock "github.com/stretchr/testify/mock"
)

// ShippingOptionUsecase is an autogenerated mock type for the ShippingOptionUsecase type
type ShippingOptionUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, shipping_option
func (_m *ShippingOptionUsecase) Create(c context.Context, shipping_option *domain.ShippingOption) error {
	ret := _m.Called(c, shipping_option)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ShippingOption) error); ok {
		r0 = rf(c, shipping_option)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ShippingOptionUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ShippingOptionUsecase) Fetch(c context.Context) ([]domain.ShippingOption, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ShippingOption
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ShippingOption, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ShippingOption); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ShippingOption)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ShippingOptionUsecase) FetchByID(c context.Context, ID string) (domain.ShippingOption, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ShippingOption
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ShippingOption, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ShippingOption); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ShippingOption)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, shipping_option
func (_m *ShippingOptionUsecase) Update(c context.Context, shipping_option *domain.ShippingOption) error {
	ret := _m.Called(c, shipping_option)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ShippingOption) error); ok {
		r0 = rf(c, shipping_option)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShippingOptionUsecase creates a new instance of ShippingOptionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShippingOptionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShippingOptionUsecase {
	mock := &ShippingOptionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
