// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/shipping"

	mock "github.com/stretchr/testify/mock"
)

// ShippingMethodCountryMappingRepository is an autogenerated mock type for the ShippingMethodCountryMappingRepository type
type ShippingMethodCountryMappingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, shipping_method_country
func (_m *ShippingMethodCountryMappingRepository) Create(c context.Context, shipping_method_country *domain.ShippingMethodCountryMapping) error {
	ret := _m.Called(c, shipping_method_country)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ShippingMethodCountryMapping) error); ok {
		r0 = rf(c, shipping_method_country)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *ShippingMethodCountryMappingRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *ShippingMethodCountryMappingRepository) Fetch(c context.Context) ([]domain.ShippingMethodCountryMapping, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.ShippingMethodCountryMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ShippingMethodCountryMapping, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ShippingMethodCountryMapping); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ShippingMethodCountryMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *ShippingMethodCountryMappingRepository) FetchByID(c context.Context, ID string) (domain.ShippingMethodCountryMapping, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.ShippingMethodCountryMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ShippingMethodCountryMapping, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ShippingMethodCountryMapping); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.ShippingMethodCountryMapping)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, shipping_method_country
func (_m *ShippingMethodCountryMappingRepository) Update(c context.Context, shipping_method_country *domain.ShippingMethodCountryMapping) error {
	ret := _m.Called(c, shipping_method_country)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ShippingMethodCountryMapping) error); ok {
		r0 = rf(c, shipping_method_country)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShippingMethodCountryMappingRepository creates a new instance of ShippingMethodCountryMappingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShippingMethodCountryMappingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShippingMethodCountryMappingRepository {
	mock := &ShippingMethodCountryMappingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
