// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// SpecificationAttributeGroupRepository is an autogenerated mock type for the SpecificationAttributeGroupRepository type
type SpecificationAttributeGroupRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, specification_attribute_group
func (_m *SpecificationAttributeGroupRepository) Create(c context.Context, specification_attribute_group *domain.SpecificationAttributeGroup) error {
	ret := _m.Called(c, specification_attribute_group)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SpecificationAttributeGroup) error); ok {
		r0 = rf(c, specification_attribute_group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *SpecificationAttributeGroupRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *SpecificationAttributeGroupRepository) Fetch(c context.Context) ([]domain.SpecificationAttributeGroup, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.SpecificationAttributeGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.SpecificationAttributeGroup, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.SpecificationAttributeGroup); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SpecificationAttributeGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *SpecificationAttributeGroupRepository) FetchByID(c context.Context, ID string) (domain.SpecificationAttributeGroup, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.SpecificationAttributeGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.SpecificationAttributeGroup, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.SpecificationAttributeGroup); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.SpecificationAttributeGroup)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, specification_attribute_group
func (_m *SpecificationAttributeGroupRepository) Update(c context.Context, specification_attribute_group *domain.SpecificationAttributeGroup) error {
	ret := _m.Called(c, specification_attribute_group)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SpecificationAttributeGroup) error); ok {
		r0 = rf(c, specification_attribute_group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSpecificationAttributeGroupRepository creates a new instance of SpecificationAttributeGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpecificationAttributeGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpecificationAttributeGroupRepository {
	mock := &SpecificationAttributeGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
