// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/directory"

	mock "github.com/stretchr/testify/mock"
)

// StateProvinceRepository is an autogenerated mock type for the StateProvinceRepository type
type StateProvinceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, state_province
func (_m *StateProvinceRepository) Create(c context.Context, state_province *domain.StateProvince) error {
	ret := _m.Called(c, state_province)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StateProvince) error); ok {
		r0 = rf(c, state_province)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *StateProvinceRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *StateProvinceRepository) Fetch(c context.Context) ([]domain.StateProvince, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.StateProvince
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.StateProvince, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.StateProvince); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StateProvince)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *StateProvinceRepository) FetchByID(c context.Context, ID string) (domain.StateProvince, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.StateProvince
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.StateProvince, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.StateProvince); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.StateProvince)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, state_province
func (_m *StateProvinceRepository) Update(c context.Context, state_province *domain.StateProvince) error {
	ret := _m.Called(c, state_province)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StateProvince) error); ok {
		r0 = rf(c, state_province)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStateProvinceRepository creates a new instance of StateProvinceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateProvinceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateProvinceRepository {
	mock := &StateProvinceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
