// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// StockQuantityChangeRepository is an autogenerated mock type for the StockQuantityChangeRepository type
type StockQuantityChangeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, stock_quantity_change
func (_m *StockQuantityChangeRepository) Create(c context.Context, stock_quantity_change *domain.StockQuantityChange) error {
	ret := _m.Called(c, stock_quantity_change)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StockQuantityChange) error); ok {
		r0 = rf(c, stock_quantity_change)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *StockQuantityChangeRepository) CreateMany(c context.Context, items []domain.StockQuantityChange) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.StockQuantityChange) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *StockQuantityChangeRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *StockQuantityChangeRepository) Fetch(c context.Context) ([]domain.StockQuantityChange, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.StockQuantityChange
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.StockQuantityChange, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.StockQuantityChange); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StockQuantityChange)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *StockQuantityChangeRepository) FetchByID(c context.Context, ID string) (domain.StockQuantityChange, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.StockQuantityChange
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.StockQuantityChange, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.StockQuantityChange); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.StockQuantityChange)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, stock_quantity_change
func (_m *StockQuantityChangeRepository) Update(c context.Context, stock_quantity_change *domain.StockQuantityChange) error {
	ret := _m.Called(c, stock_quantity_change)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StockQuantityChange) error); ok {
		r0 = rf(c, stock_quantity_change)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStockQuantityChangeRepository creates a new instance of StockQuantityChangeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockQuantityChangeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockQuantityChangeRepository {
	mock := &StockQuantityChangeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
