// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain"

	mock "github.com/stretchr/testify/mock"
)

// StoreInformationSettingsRepository is an autogenerated mock type for the StoreInformationSettingsRepository type
type StoreInformationSettingsRepository struct {
	mock.Mock
}

func (_m *StoreInformationSettingsRepository) CreateMany(c context.Context, acl_record []domain.StoreInformationSettings) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.StoreInformationSettings) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}


// Create provides a mock function with given fields: c, store_information_settings
func (_m *StoreInformationSettingsRepository) Create(c context.Context, store_information_settings *domain.StoreInformationSettings) error {
	ret := _m.Called(c, store_information_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StoreInformationSettings) error); ok {
		r0 = rf(c, store_information_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *StoreInformationSettingsRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *StoreInformationSettingsRepository) Fetch(c context.Context) ([]domain.StoreInformationSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.StoreInformationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.StoreInformationSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.StoreInformationSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StoreInformationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *StoreInformationSettingsRepository) FetchByID(c context.Context, ID string) (domain.StoreInformationSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.StoreInformationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.StoreInformationSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.StoreInformationSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.StoreInformationSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, store_information_settings
func (_m *StoreInformationSettingsRepository) Update(c context.Context, store_information_settings *domain.StoreInformationSettings) error {
	ret := _m.Called(c, store_information_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StoreInformationSettings) error); ok {
		r0 = rf(c, store_information_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStoreInformationSettingsRepository creates a new instance of StoreInformationSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreInformationSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreInformationSettingsRepository {
	mock := &StoreInformationSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
