// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/tax"

	mock "github.com/stretchr/testify/mock"
)

// TaxCategoryRepository is an autogenerated mock type for the TaxCategoryRepository type
type TaxCategoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, tax_category
func (_m *TaxCategoryRepository) Create(c context.Context, tax_category *domain.TaxCategory) error {
	ret := _m.Called(c, tax_category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TaxCategory) error); ok {
		r0 = rf(c, tax_category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *TaxCategoryRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *TaxCategoryRepository) Fetch(c context.Context) ([]domain.TaxCategory, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.TaxCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.TaxCategory, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.TaxCategory); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TaxCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *TaxCategoryRepository) FetchByID(c context.Context, ID string) (domain.TaxCategory, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.TaxCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.TaxCategory, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.TaxCategory); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.TaxCategory)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, tax_category
func (_m *TaxCategoryRepository) Update(c context.Context, tax_category *domain.TaxCategory) error {
	ret := _m.Called(c, tax_category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TaxCategory) error); ok {
		r0 = rf(c, tax_category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaxCategoryRepository creates a new instance of TaxCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaxCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaxCategoryRepository {
	mock := &TaxCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
