// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// TierPriceRepository is an autogenerated mock type for the TierPriceRepository type
type TierPriceRepository struct {
	mock.Mock
}

func (_m *TierPriceRepository) CreateMany(c context.Context, acl_record []domain.TierPrice) error {
	ret := _m.Called(c, acl_record)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.TierPrice) error); ok {
		r0 = rf(c, acl_record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Create provides a mock function with given fields: c, tier_price
func (_m *TierPriceRepository) Create(c context.Context, tier_price *domain.TierPrice) error {
	ret := _m.Called(c, tier_price)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TierPrice) error); ok {
		r0 = rf(c, tier_price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *TierPriceRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *TierPriceRepository) Fetch(c context.Context) ([]domain.TierPrice, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.TierPrice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.TierPrice, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.TierPrice); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TierPrice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *TierPriceRepository) FetchByID(c context.Context, ID string) (domain.TierPrice, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.TierPrice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.TierPrice, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.TierPrice); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.TierPrice)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, tier_price
func (_m *TierPriceRepository) Update(c context.Context, tier_price *domain.TierPrice) error {
	ret := _m.Called(c, tier_price)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TierPrice) error); ok {
		r0 = rf(c, tier_price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTierPriceRepository creates a new instance of TierPriceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTierPriceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TierPriceRepository {
	mock := &TierPriceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
