// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/seo"

	mock "github.com/stretchr/testify/mock"
)

// UrlRecordRepository is an autogenerated mock type for the UrlRecordRepository type
type UrlRecordRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, url_record
func (_m *UrlRecordRepository) Create(c context.Context, url_record *domain.UrlRecord) error {
	ret := _m.Called(c, url_record)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UrlRecord) error); ok {
		r0 = rf(c, url_record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *UrlRecordRepository) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *UrlRecordRepository) Fetch(c context.Context) ([]domain.UrlRecord, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.UrlRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.UrlRecord, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.UrlRecord); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UrlRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *UrlRecordRepository) FetchByID(c context.Context, ID string) (domain.UrlRecord, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.UrlRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.UrlRecord, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.UrlRecord); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.UrlRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, url_record
func (_m *UrlRecordRepository) Update(c context.Context, url_record *domain.UrlRecord) error {
	ret := _m.Called(c, url_record)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UrlRecord) error); ok {
		r0 = rf(c, url_record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUrlRecordRepository creates a new instance of UrlRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlRecordRepository {
	mock := &UrlRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
