// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/vendors"

	mock "github.com/stretchr/testify/mock"
)

// VendorSettingsUsecase is an autogenerated mock type for the VendorSettingsUsecase type
type VendorSettingsUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, vendor_settings
func (_m *VendorSettingsUsecase) Create(c context.Context, vendor_settings *domain.VendorSettings) error {
	ret := _m.Called(c, vendor_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VendorSettings) error); ok {
		r0 = rf(c, vendor_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *VendorSettingsUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *VendorSettingsUsecase) Fetch(c context.Context) ([]domain.VendorSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.VendorSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.VendorSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.VendorSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.VendorSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *VendorSettingsUsecase) FetchByID(c context.Context, ID string) (domain.VendorSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.VendorSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.VendorSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.VendorSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.VendorSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, vendor_settings
func (_m *VendorSettingsUsecase) Update(c context.Context, vendor_settings *domain.VendorSettings) error {
	ret := _m.Called(c, vendor_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VendorSettings) error); ok {
		r0 = rf(c, vendor_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVendorSettingsUsecase creates a new instance of VendorSettingsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVendorSettingsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *VendorSettingsUsecase {
	mock := &VendorSettingsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
