// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "earnforglance/server/domain/cms"

	mock "github.com/stretchr/testify/mock"
)

// WidgetSettingsUsecase is an autogenerated mock type for the WidgetSettingsUsecase type
type WidgetSettingsUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, widget_settings
func (_m *WidgetSettingsUsecase) Create(c context.Context, widget_settings *domain.WidgetSettings) error {
	ret := _m.Called(c, widget_settings)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WidgetSettings) error); ok {
		r0 = rf(c, widget_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: c, items
func (_m *WidgetSettingsUsecase) CreateMany(c context.Context, items []domain.WidgetSettings) error {
	ret := _m.Called(c, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.WidgetSettings) error); ok {
		r0 = rf(c, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: c, ID
func (_m *WidgetSettingsUsecase) Delete(c context.Context, ID string) error {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *WidgetSettingsUsecase) Fetch(c context.Context) ([]domain.WidgetSettings, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.WidgetSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.WidgetSettings, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.WidgetSettings); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WidgetSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: c, ID
func (_m *WidgetSettingsUsecase) FetchByID(c context.Context, ID string) (domain.WidgetSettings, error) {
	ret := _m.Called(c, ID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 domain.WidgetSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.WidgetSettings, error)); ok {
		return rf(c, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.WidgetSettings); ok {
		r0 = rf(c, ID)
	} else {
		r0 = ret.Get(0).(domain.WidgetSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, widget_settings
func (_m *WidgetSettingsUsecase) Update(c context.Context, widget_settings *domain.WidgetSettings) error {
	ret := _m.Called(c, widget_settings)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WidgetSettings) error); ok {
		r0 = rf(c, widget_settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWidgetSettingsUsecase creates a new instance of WidgetSettingsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWidgetSettingsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WidgetSettingsUsecase {
	mock := &WidgetSettingsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
