@startuml

class struct { {
}
login_controller.go --> struct {
profile_controller.go --> struct {
refresh_token_controller.go --> struct {
signup_controller.go --> struct {
task_controller.go --> struct {
affiliate.go --> struct {
base_attribute.go --> struct {
base_attribute_value.go --> struct {
blog_comment.go --> struct {
blog_post.go --> struct {
blog_post_tag.go --> struct {
blog_settings.go --> struct {
back_in_stock_subscription.go --> struct {
catalog_settings.go --> struct {
category.go --> struct {
category_template.go --> struct {
cross_sell_product.go --> struct {
manufacturer.go --> struct {
manufacturer_template.go --> struct {
predefined_product_attribute_value.go --> struct {
product.go --> struct {
product_attribute.go --> struct {
product_attribute_combination.go --> struct {
product_attribute_combination_picture.go --> struct {
product_attribute_mapping.go --> struct {
product_attribute_value.go --> struct {
product_attribute_value_picture.go --> struct {
product_category.go --> struct {
product_editor_settings.go --> struct {
product_manufacturer.go --> struct {
product_picture.go --> struct {
product_product_tag_mapping.go --> struct {
product_review.go --> struct {
product_review_helpfulness.go --> struct {
product_review_review_type_mapping.go --> struct {
product_specification_attribute.go --> struct {
product_tag.go --> struct {
product_template.go --> struct {
product_video.go --> struct {
product_warehouse_inventory.go --> struct {
related_product.go --> struct {
review_type.go --> struct {
specification_attribute.go --> struct {
specification_attribute_group.go --> struct {
specification_attribute_option.go --> struct {
stock_quantity_change.go --> struct {
tier_price.go --> struct {
widget_settings.go --> struct {
address.go --> struct {
address_attribute.go --> struct {
address_attribute_value.go --> struct {
address_settings.go --> struct {
admin_area_settings.go --> struct {
common_settings.go --> struct {
display_default_footer_item_settings.go --> struct {
display_default_menu_item_settings.go --> struct {
generic_attribute.go --> struct {
pdf_settings.go --> struct {
search_term.go --> struct {
search_term_report_line.go --> struct {
sitemap_settings.go --> struct {
sitemap_xml_settings.go --> struct {
setting.go --> struct {
best_customer_report_line.go --> struct {
customer.go --> struct {
customer_address_mapping.go --> struct {
customer_attribute.go --> struct {
customer_attribute_value.go --> struct {
customer_customer_role_mapping.go --> struct {
reward_points_history.go --> struct {
reward_points_settings.go --> struct {
country.go --> struct {
currency.go --> struct {
currency_settings.go --> struct {
exchange_rate.go --> struct {
measure_dimension.go --> struct {
measure_settings.go --> struct {
measure_weight.go --> struct {
state_province.go --> struct {
discount.go --> struct {
discount_category_mapping.go --> struct {
discount_manufacturer_mapping.go --> struct {
discount_mapping.go --> struct {
discount_product_mapping.go --> struct {
discount_requirement.go --> struct {
discount_usage_history.go --> struct {
forum.go --> struct {
forum_group.go --> struct {
forum_post.go --> struct {
forum_post_vote.go --> struct {
forum_settings.go --> struct {
forum_subscription.go --> struct {
forum_topic.go --> struct {
private_message.go --> struct {
customer_permanently_deleted.go --> struct {
gdpr_consent.go --> struct {
gdpr_log.go --> struct {
gdpr_settings.go --> struct {
language.go --> struct {
locale_string_resource.go --> struct {
localization_settings.go --> struct {
localized_property.go --> struct {
activity_log.go --> struct {
activity_log_type.go --> struct {
log.go --> struct {

@enduml